spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.104.160.226:3306/test
    username: root
    password: 123
  redis:
      # 地址
    host: 47.104.160.226
   # host: 127.0.0.1
      # 端口号
    port: 6379
      # 密码
    password: 123
      # 超时时间，单位毫秒
    timeout: 3000
      # 数据库编号
    database: 0
server:
  port: 9527


  redis:
    # 地址
    host: 192.168.56.102
    # 端口号
    port: 3306
    # 密码
    password: 123456
    # 超时时间，单位毫秒
    timeout: 3000
    # 数据库编号
    database: 0
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl