spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:
    username: 
    password: 
  redis:
      # 地址
    host: 
   # host: 
      # 端口号
    port: 6379
      # 密码
    password: 123
      # 超时时间，单位毫秒
    timeout: 3000
      # 数据库编号
    database: 0
server:
  port: 9527


  redis:
    # 地址
    host: 
    # 端口号
    port: 3
    # 密码
    password: 
    # 超时时间，单位毫秒
    timeout: 3000
    # 数据库编号
    database: 0
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
